#import "@preview/acrostiche:0.7.0": acr

= Discussion and Future Work

This thesis has developed software which takes images, encodes them via #acr("SSTV") and transmits them as audio. Two libraries have been provided to the community. `sstv` is a hardware-agnostic #acr("SSTV") encoding and decoding library supporting the most common modes and has already found real-world use by the #link("https://www.slowscan.space") website. `beacon` provides functions and abstractions which can be integrated by satellite teams into their own #acr("SSTV") system with a diverse set of input and output devices.

Real-world applicability of the software has been proven by an integration into the MOVE-IIIa #acr("SSTV") payload via `beacon-on-moveiiia` where the firmware passes all of the integration tests and fulfills all requirements.

However, the results come with some limitations. With 687.648 kB, the firmware only undercuts the @req-size by roughly 13% which leaves only a small margin for future features. In the future, the firmware size could be reduced by replacing ESP-IDF with the bare-metal `esp-hal` crate. At the time of writing `esp-hal` does not support the MIPI-CSI interface of the ESP32-P4 and can therefore not be used for the cameras @esp-hal. The choice of Rust itself also has caveats. Unlike ESP-IDF for C, the Rust support for the ESP32 is maintained by the community, meaning new peripherals are supported later or have to be accessed through raw bindings. Rust also does not have the decades of flight heritage that C has accumulated. Nevertheless, the memory guardrails outweigh these downsides for such systems. Lastly, the verification has its own limitations. The integration tests only check whether the decoded images "look" plausible instead of comparing them against a reference. Furthermore, the system has not been tested under space conditions.

Future work could expand on the features implemented in this thesis and suggested by the community in @tab-community-input. The most promising candidate is the transmission of buffered images. Community members would provide pictures for special occasions which are uploaded to the satellite and then transmitted instead of the camera captures. Another requested feature is the support for digital modes where the image quality is less suseptible to noise and higher quality images can be transmitted. Furthermore, the current implementation is entirely dependent on the pointing of the satellite to capture an interesting image. Without explicit support from the pointing system, a significant amount of captures would not feature parts of the Earth, but only the black of space or captures saturated by the Sun. A future feature could implement a metric for determining how interesting an image is and then store it for future transmission.

With `beacon` and `sstv`, future satellite teams do not have to design their their #acr("SSTV") payload software from scratch but only need to implement the hardware abstractions for their specific devices, as demonstrated by `beacon-on-tab5`. Once MOVE-IIIa is in orbit, its #acr("SSTV") images will be one of the few parts of the mission that anyone with a radio and a smartphone can receive.
