<!--
Backup slide for one thesis figure or listing (generated by scripts/backup.py):
black on white, with a table of contents of all backup slides on the left.
Frontmatter: figure ("Figure 3"), short (TOC entry), chapter (TOC group).
-->
<script setup lang="ts">
import { useNav, useSlideContext } from '@slidev/client'
import { computed } from 'vue'

const { slides, go } = useNav()
const { $page } = useSlideContext()

interface Entry { no: number, figure: string, short: string, chapter: string }

const groups = computed(() => {
  const entries: Entry[] = slides.value
    .filter(s => s.meta?.slide?.frontmatter?.layout === 'backup')
    .map((s) => {
      const fm = s.meta!.slide!.frontmatter
      return { no: s.no, figure: fm.figure, short: fm.short, chapter: fm.chapter }
    })
  const byChapter = new Map<string, Entry[]>()
  for (const e of entries)
    byChapter.set(e.chapter, [...(byChapter.get(e.chapter) ?? []), e])
  return [...byChapter]
})

const abbreviate = (figure: string) => figure.replace('Figure', 'Fig.').replace('Listing', 'Lst.')
</script>

<template>
  <div class="slidev-layout backup">
    <nav class="toc">
      <section v-for="[chapter, entries] in groups" :key="chapter">
        <div class="chapter">
          {{ chapter }}
        </div>
        <a
          v-for="e in entries"
          :key="e.no"
          :class="{ current: e.no === $page }"
          @click="go(e.no)"
        >
          <span class="num">{{ abbreviate(e.figure) }}</span>{{ e.short }}
        </a>
      </section>
    </nav>
    <main class="content">
      <slot />
    </main>
  </div>
</template>

<style>
.slidev-layout.backup {
  position: relative;
  width: 100%;
  height: 100%;
  padding: 0;
  background: #fff;
  color: #111;
  font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
}

.backup .toc {
  position: absolute;
  left: 0;
  top: 0;
  bottom: 0;
  width: 250px;
  padding: 22px 14px 22px 22px;
  border-right: 1px solid #e3e3e3;
  font-size: 10.5px;
  line-height: 1.25;
  overflow: hidden;
}

.backup .toc .chapter {
  margin: 7px 0 2px;
  font-weight: 700;
  font-size: 9.5px;
  text-transform: uppercase;
  letter-spacing: 0.06em;
}

.backup .toc section:first-child .chapter {
  margin-top: 0;
}

.backup .toc a {
  display: block;
  padding: 1px 6px;
  border-radius: 4px;
  color: #111;
  text-decoration: none;
  cursor: pointer;
  white-space: nowrap;
}

.backup .toc a:hover {
  background: #f0f0f0;
}

.backup .toc a.current {
  background: #111;
  color: #fff;
}

.backup .toc .num {
  display: inline-block;
  width: 42px;
}

.backup .content {
  position: absolute;
  left: 250px;
  right: 0;
  top: 0;
  bottom: 0;
  padding: 36px 48px 56px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 20px;
}

.backup .backup-figure {
  width: 100%;
  min-height: 0;
  max-height: 520px;
  object-fit: contain;
}

.backup .backup-caption {
  max-width: 860px;
  text-align: center;
  font-size: 17px;
  line-height: 1.4;
}

.backup .backup-caption code {
  padding: 1px 5px;
  border-radius: 4px;
  background: #ececec;
  color: #111;
  font-size: 0.88em;
}

.backup .backup-code {
  max-width: 100%;
}

.backup .backup-columns {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 24px;
}

.backup .slidev-code {
  margin: 0;
  padding: 14px 20px;
  border-radius: 6px;
  --slidev-code-line-height: 1.45;
}

/* Long shell lines wrap instead of running off the slide. */
.backup .slidev-code code {
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}

/* The deck runs in dark mode; backup slides switch Shiki to the light colours every token also carries. */
html.dark .slidev-layout.backup .shiki {
  background: #f5f5f5 !important;
  color: var(--shiki-light, inherit);
}

html.dark .slidev-layout.backup .shiki span {
  color: var(--shiki-light);
}
</style>
